### ISSUE TITLE
請修改3proxy.sh的3proyinit腳本

### ISSUE THREAD

**Issue by twfcc** [mritd/gfw.press#1]
在使用bash的 Here Document方式有些沒了反斜線 \ ，寫進去變空了，之前漏寫了的，sorry 
請修改這些地方避免bash先行解釋,當作變量或命令替換，導致系統啟動腳本沒有了stop選項

# Required-Start: \$remote_fs \$syslog
# Required-Stop: \$remote_fs \$syslog
和
kill \`ps aux | grep 3proxy | grep -v grep | awk '{print \$2}'\`

因為之前還沒更新 :(

**Comment by twfcc** [comment]
改為
kill  \`ps aux | grep 3proxy | grep -v grep | awk '{print \$2}'\`

**Comment by mritd** [comment]
我对 bash 脚本不太熟悉，已修复，感谢提出。
